channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - autopep8
  - ca-certificates
  - openssl
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - matplotlib
  - seaborn
  - certifi
